version: "{build}"

clone_folder: c:\projects\EmscriptenCMakeMinimal

image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release

platform:
  - x86

init:
  - set cMakeParams=
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set cMakeParams=-G "Visual Studio 15 2017" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" ( set cMakeParams=-G "Visual Studio 16 2019" -A "Win32")

before_build:
  - mkdir Build
  - cd Build
  - cmake %cMakeParams% ..
  - cd ..

build:
  project: c:\projects\EmscriptenCMakeMinimal\Build\EmscriptenCMakeMinimal.sln
  verbosity: minimal

after_build:
  - git clone https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - git pull
  - emsdk install latest
  - emsdk activate latest
  - emsdk install mingw-4.6.2-32bit
  - emsdk activate mingw-4.6.2-32bit
  - cd ..
  - mkdir WebApp
  - EmscriptenBuild.bat c:\projects\EmscriptenCMakeMinimal\emsdk c:\projects\EmscriptenCMakeMinimal\WebApp %configuration%
